
set (OPENNI_FOUND FALSE)

macro (use_package_openni)
    if (ROCKET_OPENNI)
        if (MSVC90)
            set (OPENNI_ROOT "C:/Program Files (x86)/OpenNI")
            if (CMAKE_CL_64)
                set (OPENNI_ROOT "C:/Program Files/OpenNI")
            endif ()
            include_directories ("${OPENNI_ROOT}/Include")
            set (OPENNI_FOUND TRUE)
        else ()
            message(FATAL_ERROR "OpenNI can only be built with VC9 at the moment!")
        endif ()
    endif()
endmacro()

macro (link_package_openni)
    if (OPENNI_FOUND)
        if (MSVC90)
            target_link_libraries (${TARGET_NAME} "${OPENNI_ROOT}/Lib/openNI.lib")
        else ()
            message(FATAL_ERROR "OpenNI can only be built with VC9 at the moment!")
        endif ()
    endif ()
endmacro ()

macro (declare_openni_defines)
    if (ROCKET_OPENNI AND OPENNI_FOUND)
        add_definitions(-DROCKET_OPENNI)
    endif()
endmacro ()
